name = "aria5-htmx"
main = "src/index-htmx.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "aria5-htmx"
database_id = "your-database-id-here"

# KV Storage Configuration (for sessions)
[[kv_namespaces]]
binding = "KV"
id = "your-kv-id-here"
preview_id = "your-kv-preview-id-here"

# Environment Variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "aria5-htmx-secret-key-change-in-production"

# Build configuration
[build]
command = "npm run build:htmx"