# Kong Gateway Configuration for Risk Management Platform
# This configuration sets up services, routes, and plugins for enterprise API management

_format_version: "3.0"

# Services Definition
services:
  - name: risk-management-api
    host: risk-management-app
    port: 3000
    protocol: http
    path: /
    connect_timeout: 30000
    read_timeout: 30000
    write_timeout: 30000
    retries: 3

# Routes Configuration
routes:
  # API Routes (Authenticated)
  - name: api-routes
    service: risk-management-api
    protocols:
      - http
      - https
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
    paths:
      - /api
    regex_priority: 100
    strip_path: false
    preserve_host: false

  # Static Assets Routes (Public)
  - name: static-routes
    service: risk-management-api
    protocols:
      - http
      - https
    methods:
      - GET
    paths:
      - /static
    regex_priority: 90
    strip_path: false
    preserve_host: false

  # Main Application Route (Public)
  - name: app-routes
    service: risk-management-api
    protocols:
      - http
      - https
    methods:
      - GET
      - POST
    paths:
      - /
      - /login
    regex_priority: 80
    strip_path: false
    preserve_host: false

# Plugins Configuration
plugins:
  # Global CORS Plugin
  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:8080"
        - "https://dmt-risk-assessment.pages.dev"
        - "https://*.pages.dev"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Requested-With
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 86400
      preflight_continue: false

  # Global Rate Limiting (Distributed with Redis)
  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      day: 10000
      policy: redis
      redis_host: kong-redis
      redis_port: 6379
      redis_timeout: 2000
      hide_client_headers: false

  # Request/Response Logging
  - name: file-log
    config:
      path: /tmp/kong_logs.jsonl
      reopen: true

  # Security Headers
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Content-Type-Options:nosniff"
          - "X-Frame-Options:DENY"
          - "X-XSS-Protection:1; mode=block"
          - "Strict-Transport-Security:max-age=31536000; includeSubDomains"
          - "Referrer-Policy:strict-origin-when-cross-origin"

  # API Routes Specific Plugins
  - name: jwt
    route: api-routes
    config:
      uri_param_names:
        - jwt
      cookie_names:
        - jwt
      header_names:
        - authorization
      claims_to_verify:
        - exp
        - nbf
      key_claim_name: iss
      secret_is_base64: false
      run_on_preflight: false

  # Enhanced Rate Limiting for API Routes
  - name: rate-limiting
    route: api-routes
    config:
      minute: 50
      hour: 500
      day: 5000
      policy: redis
      redis_host: kong-redis
      redis_port: 6379
      redis_timeout: 2000
      hide_client_headers: false

  # Request Size Limiting
  - name: request-size-limiting
    route: api-routes
    config:
      allowed_payload_size: 128  # 128KB max request size

  # IP Restriction (Optional - Configure as needed)
  # - name: ip-restriction
  #   route: api-routes
  #   config:
  #     allow:
  #       - "127.0.0.1"
  #       - "10.0.0.0/8"
  #       - "172.16.0.0/12"
  #       - "192.168.0.0/16"

# Consumers (API Keys/JWT Issuers)
consumers:
  - username: risk-management-system
    custom_id: rm-system-001

# JWT Credentials
jwt_secrets:
  - consumer: risk-management-system
    key: risk-management-issuer
    secret: your-jwt-secret-key-here-change-in-production

# Key Auth (Alternative to JWT)
keyauth_credentials:
  - consumer: risk-management-system
    key: your-api-key-here-change-in-production